// Emit pixhist-core.generated.js — the pixel classifier, lifted out of bulk.js, as a standalone file.
//
// WHY THIS EXISTS: compute-table.js reads the PIXHIST-CORE region straight out of bulk.js so the table
// can never drift from the live engine. That works on a dev machine, but bulk.js is the PRIVATE dev
// source — it is full of working notes and is deliberately not published — so the nightly GitHub
// Action had nothing to read and died instantly.
//
// This writes the extracted region to a committed file instead. It is GENERATED, never hand-edited, so
// the drift-proof property survives: the bytes still come from bulk.js. It only changes when a
// calibration knob changes, which always comes with a _PIXHIST_KEY bump — and the table is stamped
// with that version, so a stale core can never be mistaken for a current one.
//
// The body is stored as a JSON string, NOT a template literal: the region contains backticks and ${…}
// and embedding it in a template would corrupt it.
//
// Run whenever the PIXHIST-CORE region or _PIXHIST_KEY changes:  node emit-core.js
'use strict';
const fs = require('fs');
const path = require('path');

const BULK = path.join(__dirname, '..', '..', 'bulk.js');
const OUT = path.join(__dirname, 'pixhist-core.generated.js');
const START = 'PIXHIST-CORE-START';
const END = 'PIXHIST-CORE-END';

function main() {
  const src = fs.readFileSync(BULK, 'utf8');
  const a = src.indexOf(START);
  const b = src.indexOf(END);
  if (a < 0 || b < 0 || b < a) throw new Error('PIXHIST-CORE markers not found in bulk.js');
  const body = src.slice(src.indexOf('\n', a) + 1, src.lastIndexOf('\n', b));

  const vm = src.match(/_PIXHIST_KEY\s*=\s*'([^']+)'/);
  if (!vm) throw new Error("could not read _PIXHIST_KEY from bulk.js");

  // prove it still evaluates standalone before shipping it
  const api = new Function(body + '\n;return { _pixHistFromData, _pixFamily };')();
  if (typeof api._pixHistFromData !== 'function') throw new Error('_pixHistFromData missing from the extracted region');

  const out =
    '// GENERATED by tools/color-table/emit-core.js — DO NOT EDIT.\n' +
    '// The pixel classifier lifted verbatim from bulk.js so CI can build the colour table without the\n' +
    '// private dev source. Re-run emit-core.js whenever the PIXHIST-CORE region or _PIXHIST_KEY changes.\n' +
    "'use strict';\n" +
    'module.exports.v = ' + JSON.stringify(vm[1]) + ';\n' +
    'module.exports.body = ' + JSON.stringify(body) + ';\n';
  fs.writeFileSync(OUT, out);

  console.log('version:', vm[1]);
  console.log('core body:', body.length, 'bytes');
  console.log('wrote', OUT);
}

main();
