// Compress cache/batch-results.json into the bulk.js table: bodyId → box center, plus a
// speciesId → standard-bodyId fallback map. Verifies the constant-size finding and reports
// anything that deviates before emitting.
'use strict';
const fs = require('fs');
const path = require('path');

const CACHE = path.join(__dirname, 'cache');
const results = JSON.parse(fs.readFileSync(path.join(CACHE, 'batch-results.json')));
const petTypes = JSON.parse(fs.readFileSync(path.join(CACHE, 'pet_types.json')));
const names = JSON.parse(fs.readFileSync(path.join(CACHE, 'names.json')));

const ok = results.filter(r => !r.failed && !r.validation);

// 1. size constancy check
const sizes = {};
ok.forEach(r => { const k = r.size.toFixed(3); sizes[k] = (sizes[k] || 0) + 1; });
console.log('size distribution:', JSON.stringify(sizes));
const sizeMode = +Object.entries(sizes).sort((a, b) => b[1] - a[1])[0][0];
const deviants = ok.filter(r => Math.abs(r.size - sizeMode) > 0.01);
deviants.forEach(r => console.log('  SIZE DEVIANT', r.label, 'body', r.bodyId, 'size', r.size, 'score', r.score));

// 2. standard body per species = the body shared by the most pet_types rows of that species
const stdBody = {};
{
  const counts = {}; // species -> body -> n
  petTypes.forEach(r => {
    counts[r.species_id] = counts[r.species_id] || {};
    counts[r.species_id][r.body_id] = (counts[r.species_id][r.body_id] || 0) + 1;
  });
  Object.entries(counts).forEach(([sp, m]) => {
    stdBody[sp] = +Object.entries(m).sort((a, b) => b[1] - a[1])[0][0];
  });
}

// 3. emit — low-score rows were VISUALLY VERIFIED correct (cache/proof-flagged-*.png, 2026-07-06:
// all 25 are exact matches; Neopets' own 50s are just blurrier for 8-bit/Origami/baby art, which
// depresses NCC) — so they're INCLUDED. Only structural failures fall back to the species standard.
const byBody = {};
let flaggedIn = 0;
ok.forEach(r => {
  if (r.review) { flaggedIn++; console.log('  include (low NCC, visually verified)', r.label, 'body', r.bodyId, 'score', r.score); }
  byBody[r.bodyId] = [+(r.x + r.size / 2).toFixed(4), +(r.y + r.size / 2).toFixed(4)];
  if (Math.abs(r.size - sizeMode) > 0.01) byBody[r.bodyId].push(+r.size.toFixed(4)); // rare per-body size override
});
// species std fallback boxes (species whose standard body IS in the table)
const stdOk = {};
Object.entries(stdBody).forEach(([sp, b]) => { if (byBody[b] != null) stdOk[sp] = b; });

console.log('table bodies:', Object.keys(byBody).length, '· incl. visually-verified low-NCC:', flaggedIn,
  '· species std coverage:', Object.keys(stdOk).length + '/' + Object.keys(stdBody).length);

const snippet =
  '    // ── Neoboards Active Box table (COMPUTED, do not hand-edit) ──────────────────────────────\n' +
  '    // Generated by tools/active-box (see its README for the refresh procedure). Verified by\n' +
  '    // pixel-identity against Neopets\' own baked 50×50 avatars: the active box is a SQUARE crop\n' +
  '    // of the render — entries are [cx, cy] (fractions of the 600×600 canvas; render frame ==\n' +
  '    // canvas frame, verified identity) with size ' + sizeMode.toFixed(3) + ' of the frame; SPECIAL bodies (8-bit,\n' +
  '    // mutant, maraquan, Origami, Chia fruits…) carry their own size as a third element.\n' +
  '    // Mood/pose-invariant. Missing bodies (new/styled) fall back to the species standard body.\n' +
  '    const OE_ABOX_SIZE = ' + sizeMode.toFixed(3) + ';\n' +
  '    const OE_ABOX_BY_BODY = ' + JSON.stringify(byBody) + ';\n' +
  '    const OE_ABOX_STD_BODY = ' + JSON.stringify(stdOk) + ';\n';
fs.writeFileSync(path.join(CACHE, 'table-snippet.js'), snippet);
console.log('wrote cache/table-snippet.js (' + snippet.length + ' bytes)');
